#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	i=$(( i + 1 ))
if [ $i == 10 ]
then
	echo "Hi"
fi
done
